### ISSUE TITLE
Font cutoff

### ISSUE THREAD

**Issue by sumajoo** [supermemoryai/opensearch-ai#4]
Maybe a padding or custom font issue:

<img width="565" alt="image" src="https://github.com/user-attachments/assets/f2e59660-e9b3-4169-99c7-f38d1d1de652">

**Comment by Dhravya** [comment]
Yeah that font is weird

**Comment by mhetreayush** [comment]
@Dhravya as rightly pointed out by @sumajoo, there is no **cut-off** as such, the font itself is that way, Attaching an image of the charset.

https://abduzeedo.com/milling-sans-modern-take-typography-and-font-design

![milling-font](https://github.com/user-attachments/assets/5ac6bfc2-9969-4b56-a712-e6de7f598ea2)


We can close this issue here.
